[package]
name = "blackbird"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
wgpu = "27.0.1"
winit = "0.30.12"
tokio = { version = "1.45.0", features = ["rt", "rt-multi-thread"] }
